### ISSUE TITLE
Bug - system tray doesn't appear if VDU autostart on login

### ISSUE THREAD

**Issue by taprobane99** [digitaltrails/vdu_controls#19] opened 2022-04-12 13:52 UTC
if i add vdu to the autostart apps in KDE the system tray icon doesn't appear although VDU does open. but when I open vdu manually the system tray icon does appear.

**Comment by digitaltrails** [comment] 2022-04-12 20:48
> if i add vdu to the autostart apps in KDE the system tray icon doesn't appear although VDU does open. but when I open vdu manually the system tray icon does appear.

I presume you are running Wayland?  It's really helpful to know if wayland is involved because it has far more implementations and quirks than X11.  KDE/Plasma in particular, is really not production ready under Wayland. (I don't use Wayland except for some testing.)   So I've assumed you're running wayland, and investigated according.

Under X11, there is no need to use autostart.  In X11, if vdu_controls is running at exit, it will automatically be restored at the next X11 login.  The KDE/Plasma/Qt folk have not yet figured out how to get automatic restoration Wayland to work the same way as X11. 

Also under Wayland, KDE/Plasma seems not to have made the tray available during the autostart phase of login.  So, under Wayland, during an autostart, vdu_controls finds there is no system tray available and configures itself accordingly.  Under X11, the tray is available during autostart, so there shouldn't be any problem (in at least in the plasma releases made in the last year - I haven't tested vdu_controls in old KDE/plasma environments).  

Potentially you could workaround the issue by have autostart run a script that starts a process in the background that waits long enough for plasma to complete initialisation, then starts vdu_controls.

What I might be able to do is add some code to vdu_controls that detects a Wayland session and sleeps a while during startup to see if a tray eventually becomes available.  

**Please let me know if you are running under Wayland, I won't start looking at the code until you've confirmed the above analysis is correct.**

**Comment by taprobane99** [comment] 2022-04-12 20:54
Yes, you guessed right. Wayland.

**Comment by digitaltrails** [comment] 2022-04-12 22:02
Fixed by 2723ef2, release [v1.6.4](https://github.com/digitaltrails/vdu_controls/releases/tag/v1.6.4).

**Comment by digitaltrails** [comment] 2022-04-14 05:26
Assuming the fix solved the issue (works for me).

**Closed** 2022-04-14 05:25 UTC
