### ISSUE TITLE
[Feature Request] Add option to open main interface from tray icon

### ISSUE THREAD

**Issue by yochananmarqos** [digitaltrails/vdu_controls#18] opened 2022-04-08 22:57 UTC
As it stands, the application loads to tray by default without using the `--system-tray` option. I used to be able to double-click the tray icon to open it, now nothing happens after updating to GNOME 42. 

Another issue: Choosing About or Help then closing those dialogs exits the application completely.

**Comment by digitaltrails** [comment] 2022-04-08 23:18
A fresh install (or in the absence of any .config/vdu_control_files) should not use the system tray.  I'll check.

I'm not sure I have gnome 42.  I'm pretty much gnome illiterate.   I may need to build a vm or update one.  As I understand it the tray is an add-on plugin in gnome.  The tray seems to work for deepin and KDE,.could it be the plugin needs updating for gnome 42.  Might also be a Qt issue (it's supposed to handle this stuff for me).

The _exiting the app completely issue_... is that new to gnome 42 too?  I did try running it under gnome a while back, I can't recall it being a problem then, but I don't formally note what has been tested where.

**Comment by digitaltrails** [comment] 2022-04-08 23:44
Testing on KDE...

I just confirmed that a fresh install of the latest version does not use the system tray - unless of course there are existing .config/vdu_controls/... configuration files that specify it..  So I'm puzzled.  Even in gnome 42 this should be the case.

Also, about and help appear to be working properly. So doubly puzzled.  But I could see that if vdu_controls is running out of the tray, and no working properly, other issues might also be present.  

If vde_controls isn't run out of the tray, do the non-tray problems go away?  In which case, there's probably some Qt/tray/Gnome42 compatibility issue.   

Given gnome doesn't really officially support a tray, perhaps I should detect gnome and just always disable any tray related code.  But I gather it's quite common for folk to add a tray extension, so that's probably not the right way to go either.

**Comment by yochananmarqos** [comment] 2022-04-08 23:48
I'm using `system-tray-enabled = yes` in the config file, but that should only enable it, not make it start to the tray by default, right? Well, I just set it to `no` and the main application opened. However, without the tray icon, there's no way to access Presets, Grey scale, Settings, About and Help.

> could it be the plugin needs updating for gnome 42

Nope, it's updated to [42](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases/tag/v42).

Either way, my feature request still stands. It would be nice to have a menu option to open it from the tray.

ddcutil 1.2.2
Python 3.10.4
PyQt5 5.15.6
Qt5 Multimedia 5.15.3

**Comment by digitaltrails** [comment] 2022-04-09 00:16
> I'm using `system-tray-enabled = yes` in the config file, but that should only enable it, not make it start to the tray by default, right? Well, I just set it to `no` and the main application opened. However, without the tray icon, there's no way to access Presets, Grey scale, Settings, About and Help.

No that's the intent, if the tray is enabled, it should start there.  If the tray is not enabled it should never use the tray - that's for non-tray desktops.  

The context-menu (help, presets,etc) should be available via the right-mouse when hovering over the main UI (in any clear space, free of controls).
> 
> > could it be the plugin needs updating for gnome 42
> 
> Nope, it's updated to [42](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases/tag/v42).

My guess is that Qt, pyqt, and the updated tray extension do not get along.  Do you use any other Qt tray apps?  

I will try to update an openSUSE VM to gnome 42.  Then I will try and get the tray extension going.  I never used it before, I just assumed that Qt handled all the cross platform stuff flawlessly.  I presume it's tray behaviour was fine in gnome before 42, so my guess is the updated plugin works differently.  Vdu_controls certainly have no platform specific code - same code all platforms.  I did amend the code to avoid some Qt wayland quirks, maybe there are gnome Qt quirks too.  I shall see.

> 
> > perhaps I should detect gnome and just always disable any tray related code
> 
> Please do not do that unless you add a menu to the main application to access the missing options.
> 
> Either way, my feature request still stands. It would be nice to have a menu option to open it from the tray.

Well it should work just like it does in Deepin or Plasma.  If it doesn't perhaps I can raise bugs with the Qt folk.

In the meantime the right-mouse should get you back in action.  If gnome42 has right mouse issues,  it might be time for me to add a hamburger menu, I was planning too, I just haven't got around to it.

> 
> ddcutil 1.2.2 Python 3.10.4 PyQt5 5.15.6 Qt5 Multimedia 5.15.3

**Comment by yochananmarqos** [comment] 2022-04-09 00:26
> The context-menu (help, presets,etc) should be available via the right-mouse when hovering over the main UI (in any clear space, free of controls).

Ah, never noticed that. I've never seen an application have that functionality, so I never would have noticed. 

> it might be time for me to add a hamburger menu

That would be more intuitive. 

> I presume it's tray behaviour was fine in gnome before 42

Yes, it was up to 41.5.

> Do you use any other Qt tray apps?

Yes: Telegram, qBittorrent, Polychromatic and Clight GUI. The all work as expected.

**Comment by digitaltrails** [comment] 2022-04-09 00:58
> > The context-menu (help, presets,etc) should be available via the right-mouse when hovering over the main UI (in any clear space, free of controls).
> 
> Ah, never noticed that. I've never seen an application have that functionality, so I never would have noticed.

Good news.  Glad you're back in action.

> 
> > it might be time for me to add a hamburger menu
> 
> That would be more intuitive.

Noted.

> 
> > I presume it's tray behaviour was fine in gnome before 42
> 
> Yes, it was up to 41.5.
> 
> > Do you use any other Qt tray apps?
> 
> Yes: Telegram, qBittorrent, Polychromatic and CLight GUI. The all work as expected.
> 
> EDIT: Just noticed CLight GUI no longer opens the main application double-clicking on the tray icon like before, either.

OK, thanks.  Good to know its now just pyqt apps.  These other apps may be points of comparison when I get deeper into it.  I have a few other things on the boil at the moment, so I can't be sure of when any progress might be forthcoming.  I suspect I should add a hamburger menu first - I would hope that could be done quickly, where as finding the source of the curious behaviour may turn into a can of worms.

**Comment by digitaltrails** [comment] 2022-04-09 08:45
As a first step I've added a hamburger menu and tidied up the bottom of the main window layout.  This has been pushed as 022bc49, but I'll test it at home a bit more before creating a formal release (probably tomorrow or Monday GMT+12). 

![Screenshot_20220409_203929](https://user-images.githubusercontent.com/5510901/162564031-ccf7bc92-04cc-4762-9f1e-20fd4c80edf3.png)
.

**Comment by taprobane99** [comment] 2022-04-10 21:36
The hamburger menu and circular arrows appear blurry on a 4k monitor.

**Comment by digitaltrails** [comment] 2022-04-11 04:15
> The hamburger menu and circular arrows appear blurry on a 4k monitor.

Not on my 4K monitor.   Answers to the following questions might help figure out what is going on?

1. Are you scaling your monitor?  I don't scale, I adjust the font and icon sizes to suit the resolution.  
2. Are the brightness and contrast icons also blurry?  (They brightness and contrast are labels, whereas the refresh and hamburger-menu are part of a QToolbar)

**Comment by digitaltrails** [comment] 2022-04-11 21:36
> The hamburger menu and circular arrows appear blurry on a 4k monitor.

I reproduced the toolbar blurry icons by setting up an X11 login with a 200% scaled desktop for my own 4K monitor.  After much googling I discovered that Qt doesn't enable HiDPI toolbar icons by default (just for toolbars?!).  So the answer is a one line of code to call at startup.  I've pushed the change, so replacing your installed vdu_controls with the latest git vdu_controls.py should resolve the problem.   I may not make a new release until I've accumulated more changes.

**Comment by digitaltrails** [comment] 2022-04-12 20:50
> The hamburger menu and circular arrows appear blurry on a 4k monitor.

Can you test and confirm that the fix has worked.  Or can you confirm that you were running with a display scaled to more than 100%.

**Comment by taprobane99** [comment] 2022-04-12 20:54
i am running a display with 200% scaling.

**Comment by digitaltrails** [comment] 2022-06-10 20:41
Assuming the fixes are OK.

**Comment by yochananmarqos** [comment] 2022-06-11 00:17
@digitaltrails Not exactly. My issue was hijacked by @digitaltrails.

The subject of the issue in the title still has not been addressed. However, I can open the Help and About dialogs from the window normally now. However, When choosing them from the tray icon, the program may or may not actually exit, but the tray icon disappears after closing the dialog. There is nothing related in the debug output as it only seems to log ddcutil items.

**Comment by digitaltrails** [comment] 2022-06-11 00:33
**Add option to open main interface from tray icon**

Perhaps we need to clarify the requirements.  In respect to opening the main interface, left mouse clicking on the tray icon should open or close the main interface (on KDE and deepin at least).  In respect to having an obvious way to access the presets from the main interface, there is now a hamburger menu as well as right-mouse-button.

In respect to gnome, I don't think there is a standard tray, so I'm not sure what I can do to support whatever trays there are out there if they don't work in a way that function with the Qt API's.  But if the left-mouse-click to open the main interface does not work, perhaps I could add another item to the context menu.

**Comment by yochananmarqos** [comment] 2022-06-11 00:42
> the left-mouse-click to open the main interface does not work

Indeed. Left-click and right-click both do the same thing: open the context menu. The same occurs with other PyQt5 applications like Polychromatic, but it has a context menu item to open the main interface. Regular Qt applications like Telegram and QBittorrent do toggle the interface left-clicking.

**Comment by digitaltrails** [comment] 2022-06-11 01:12
> > the left-mouse-click to open the main interface does not work
> 
> Indeed. Left-click and right-click both do the same thing: open the context menu. The same occurs with other PyQt5 applications like Polychromatic, but it has a context menu item to open the main interface. Regular Qt applications like Telegram and QBittorrent do toggle the interface left-clicking.

Some points need clarification...

Is this in respect to gnome?  Because on my KDE desktop the left mouse button and right mouse button in the tray do different things - the left mouse button often opens the application, or in other cases opens a main operations menu, and the right mouse button often opens some configuration related menu or item.  

Also, it sounds like, unlike KDE, on gnome, closing things opened from the tray can sometimes/always (?) shut down the application. 

If we are only talking about gnome, are these behaviours new? Or has gnome always worked this way?  Or is this specific to particular tray implementation (I believe there isn't a standard one)?

I'm open to the idea of trying to support a popular variant of a gnome desktop that a distro delivers out of the box with a tray, one that I can install in a VM.   I can't support tray add-ons that have to be separately installed - I don't want to have to learn that much about gnome or each tray implementation.

Perhaps under gnome I should make the left and right mouse do the same thing - bring up a context menu.  Plus if gnome is detected, add an extra context item to bring up the main interface.  But would that break other gnome tray implementations, or other gnomed-based desktops where the tray works in the same way as KDE?

**Comment by yochananmarqos** [comment] 2022-06-11 01:24
I'm about to step away from the PC for the night, but I'll leave a short answer for now. Yes, this is on GNOME 42.2. If you want to quickly test in a VM, Manjaro GNOME ships the Appindicator Support extension by default already enabled.

**Comment by digitaltrails** [comment] 2022-06-11 01:34
> I'm about to step away from the PC for the night, but I'll leave a short answer for now. Yes, this is on GNOME 42.2. If you want to quickly test in a VM, Manjaro GNOME ships the Appindicator Support extension by default already enabled.

Thanks, I'll give that shot - the house has just been upgraded to unlimited 300/100 Mbps fibre, so it's a good excuse for a download.

**Comment by digitaltrails** [comment] 2022-06-11 03:36
> > I'm about to step away from the PC for the night, but I'll leave a short answer for now. Yes, this is on GNOME 42.2. If you want to quickly test in a VM, Manjaro GNOME ships the Appindicator Support extension by default already enabled.
> 
> Thanks, I'll give that shot - the house has just been upgraded to unlimited 300/100 Mbps fibre, so it's a good excuse for a download.

Thanks for suggesting Manjaro - that made things easy, I used vdu_controls from the AUR to haul in all the required dependencies.

OK - gnome is weird.  I've found the middle mouse button acts like the left mouse button and opens/closes the main interface.  It gets weirder, if you do use the middle mouse button to open the main interface and leave it showing, then closing about/help/... works properly, even when invoked from the system tray - so maybe a gnome app closes when the last visible window is closed (or something like that).  Anyway, at least I have something I can hack around with going forward.  Stopping for the day while I'm ahead.

**Comment by yochananmarqos** [comment] 2022-06-11 17:50
> I've found the middle mouse button acts like the left mouse button and opens/closes the main interface.

I never thought to try that. That's odd that it works for this program and no other I use.

**Comment by digitaltrails** [comment] 2022-06-11 20:14
> > I've found the middle mouse button acts like the left mouse button and opens/closes the main interface.
> 
> I never thought to try that. That's odd that it works for this program and no other I use.

Yes, it's clearly not the right solution.  It appears gnome's concept of system tray behaviour differs from KDE/deepin.  I will have to add a "control panel" item to the menu.  The same context menu is used by the the hamburger-menu and control-panel right-mouse action, so I need to ponder whether or not to somehow hide the "control panel" menu item when the menu is pulled up by those actions.  

I have successfully prevent the help/about/... popups from closing the application by also popping up the main control-panel.  As long as the main control-panel is visible, closing the other pop-ups won't terminate the application.  So it seems in gnome Qt hiding a window that is associated with the tray is kind of equivalent to it not existing at all.  I'm looking for an event or signal I can block, which might be better than bringing up the main panel, but no luck yet.

**Closed** 2022-06-11 21:33 UTC

**Comment by digitaltrails** [comment] 2022-06-12 00:47
Released in https://github.com/digitaltrails/vdu_controls/releases/tag/v1.6.7

**Comment by digitaltrails** [comment] 2022-06-12 21:02
Note 1.6.7 has a bug which stops presets from being restored/saved, fixed by 1.6.8.

**Comment by yochananmarqos** [comment] 2022-06-12 21:23
Thanks for spending the time to address this issue. Everything is now working as expected. 

FYI, I updated the AUR package to 1.6.8  5 minutes before your comment. :stuck_out_tongue:

**Comment by digitaltrails** [comment] 2022-06-12 21:29
> Thanks for spending the time to address this issue. Everything is now working as expected.
> 
> FYI, I updated the AUR package to 1.6.8 5 minutes before your comment. stuck_out_tongue

Yes, I noticed the AUR entry tick over.  I just happened to be checking what the AUR had after releasing 1.6.8.  The quick uptake had me convinced the process must be automatic.

Thanks again for pointing me to a gnome with a pre-canned tray.

**Comment by yochananmarqos** [comment] 2022-06-12 21:38
> The quick uptake had me convinced the process must be automatic.

:rofl: You're not the first to think I was a bot since I'm so fast during my waking hours[^1].
 
[^1]:  Sometimes I work on PKGBUILDs in my sleep, but I can never figure out what changes I made when I wake up.
